{% set name = "pyproject-flake8" %}
{% set version = "6.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 6da8e5a264395e0148bc11844c6fb50546f1fac83ac9210f7328664135f9e70f

build:
  entry_points:
    - pflake8=pflake8.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - flit-core >=3.2,<4
    - pip
    - python >=3.8.1
  run:
    - python >=3.8.1
    - tomli
    - flake8 ==6.0.0

test:
  imports:
    - pflake8
  commands:
    - pip check
    - pflake8 --help
  requires:
    - pip

about:
  home: https://github.com/csachs/pyproject-flake8
  summary: Monkey patching wrapper to connect flake8 with pyproject.toml configuration
  license: Unlicense
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
